### PR TITLE
Add index page for GitHub Pages

### PR DESCRIPTION
**Pull request by jamesog**
This is a modified version of the original website, with most of the
information removed and linking to the GitHub wiki and source code
instead.

Some basic information about the project has been retained on the page
to give visitors an overview of what the project's about rather than
diving straight into the source code or wiki.

### CODE REVIEW

**Comment by jamesog** [comment]
@qris I thought I'd try this out for boxbackup.github.io in case we want to point the boxbackup.org domain there. Let me know what you think.

**Review by qris — APPROVED** [review]
Thanks! I would remove information about the latest stable release version number, since people should always be downloading master now (so we can link to that instead), and the PGP signing key (since I'm not signing releases any more).

**Comment by jamesog** [comment]
Sure, I can make those changes. The benefit to linking to a release tarball is that autoconf has already been run (i.e. `configure` is generated). Is that no longer being used / supported?

**Comment by qris** [comment]
I don't think that should be a show-stopper, or that we should encourage
people to run ancient versions.

I think that many projects require you to run a bootstrap script these
days. We could even build packages with autoconf pre-run if it's really a
problem.

Thanks, Chris.

**Pull request merged**
